[frontend]
frontend1 ansible_host=13.220.69.103 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/sushmitha-voting-key.pem ansible_python_interpreter=/usr/bin/python3

[backend]
backend1 ansible_host=10.20.2.91 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/sushmitha-voting-key.pem ansible_python_interpreter=/usr/bin/python3

[database]
database1 ansible_host=10.20.2.64 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/sushmitha-voting-key.pem ansible_python_interpreter=/usr/bin/python3

[private:children]
backend
database

[private:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/sushmitha-voting-key.pem -o IdentitiesOnly=yes -W %h:%p ubuntu@13.220.69.103"'
